package c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libio.h:1466</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _IO_marker extends Structure {
	/** C type : _IO_marker* */
	public _IO_marker.ByReference _next;
	/** C type : _IO_FILE* */
	public c._IO_FILE.ByReference _sbuf;
	/** if _pos < 0, it points to _buf->eBptr()+_pos. FIXME comment */
	public int _pos;
	public _IO_marker() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("_next", "_sbuf", "_pos");
	}
	/**
	 * @param _next C type : _IO_marker*<br>
	 * @param _sbuf C type : _IO_FILE*<br>
	 * @param _pos if _pos < 0, it points to _buf->eBptr()+_pos. FIXME comment
	 */
	public _IO_marker(_IO_marker.ByReference _next, c._IO_FILE.ByReference _sbuf, int _pos) {
		super();
		this._next = _next;
		this._sbuf = _sbuf;
		this._pos = _pos;
	}
	public static class ByReference extends _IO_marker implements Structure.ByReference {
		
	};
	public static class ByValue extends _IO_marker implements Structure.ByValue {
		
	};
}
