package c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bits/sigcontext.h:572</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _xmmreg extends Structure {
	/** C type : __uint32_t[4] */
	public int[] element = new int[4];
	public _xmmreg() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("element");
	}
	/** @param element C type : __uint32_t[4] */
	public _xmmreg(int element[]) {
		super();
		if ((element.length != this.element.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.element = element;
	}
	public static class ByReference extends _xmmreg implements Structure.ByReference {
		
	};
	public static class ByValue extends _xmmreg implements Structure.ByValue {
		
	};
}
