package c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bits/sigcontext.h:633</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _xstate extends Structure {
	/** C type : _fpstate */
	public _fpstate fpstate;
	/** C type : _xsave_hdr */
	public _xsave_hdr xstate_hdr;
	/** C type : _ymmh_state */
	public _ymmh_state ymmh;
	public _xstate() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("fpstate", "xstate_hdr", "ymmh");
	}
	/**
	 * @param fpstate C type : _fpstate<br>
	 * @param xstate_hdr C type : _xsave_hdr<br>
	 * @param ymmh C type : _ymmh_state
	 */
	public _xstate(_fpstate fpstate, _xsave_hdr xstate_hdr, _ymmh_state ymmh) {
		super();
		this.fpstate = fpstate;
		this.xstate_hdr = xstate_hdr;
		this.ymmh = ymmh;
	}
	public static class ByReference extends _xstate implements Structure.ByReference {
		
	};
	public static class ByValue extends _xstate implements Structure.ByValue {
		
	};
}
