package c;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bits/sigcontext.h:620</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sigcontext extends Structure {
	/** C type : __uint64_t */
	public NativeLong r8;
	/** C type : __uint64_t */
	public NativeLong r9;
	/** C type : __uint64_t */
	public NativeLong r10;
	/** C type : __uint64_t */
	public NativeLong r11;
	/** C type : __uint64_t */
	public NativeLong r12;
	/** C type : __uint64_t */
	public NativeLong r13;
	/** C type : __uint64_t */
	public NativeLong r14;
	/** C type : __uint64_t */
	public NativeLong r15;
	/** C type : __uint64_t */
	public NativeLong rdi;
	/** C type : __uint64_t */
	public NativeLong rsi;
	/** C type : __uint64_t */
	public NativeLong rbp;
	/** C type : __uint64_t */
	public NativeLong rbx;
	/** C type : __uint64_t */
	public NativeLong rdx;
	/** C type : __uint64_t */
	public NativeLong rax;
	/** C type : __uint64_t */
	public NativeLong rcx;
	/** C type : __uint64_t */
	public NativeLong rsp;
	/** C type : __uint64_t */
	public NativeLong rip;
	/** C type : __uint64_t */
	public NativeLong eflags;
	public short cs;
	public short gs;
	public short fs;
	public short __pad0;
	/** C type : __uint64_t */
	public NativeLong err;
	/** C type : __uint64_t */
	public NativeLong trapno;
	/** C type : __uint64_t */
	public NativeLong oldmask;
	/** C type : __uint64_t */
	public NativeLong cr2;
	/** C type : field1_union */
	public field1_union field1;
	/** C type : __uint64_t[8] */
	public NativeLong[] __reserved1 = new NativeLong[8];
	/** <i>native declaration : bits/sigcontext.h:619</i> */
	public static class field1_union extends Union {
		/** C type : _fpstate* */
		public c._fpstate.ByReference fpstate;
		/** C type : __uint64_t */
		public NativeLong __fpstate_word;
		public field1_union() {
			super();
		}
		/** @param fpstate C type : _fpstate* */
		public field1_union(c._fpstate.ByReference fpstate) {
			super();
			this.fpstate = fpstate;
			setType(c._fpstate.ByReference.class);
		}
		/** @param __fpstate_word C type : __uint64_t */
		public field1_union(NativeLong __fpstate_word) {
			super();
			this.__fpstate_word = __fpstate_word;
			setType(NativeLong.class);
		}
		public static class ByReference extends field1_union implements Structure.ByReference {
			
		};
		public static class ByValue extends field1_union implements Structure.ByValue {
			
		};
	};
	public sigcontext() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "rdi", "rsi", "rbp", "rbx", "rdx", "rax", "rcx", "rsp", "rip", "eflags", "cs", "gs", "fs", "__pad0", "err", "trapno", "oldmask", "cr2", "field1", "__reserved1");
	}
	public static class ByReference extends sigcontext implements Structure.ByReference {
		
	};
	public static class ByValue extends sigcontext implements Structure.ByValue {
		
	};
}
