package c;
import c.CLibrary.t_uscalar_t;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : x86_64-linux-gnu/bits/stropts.h:92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class strfdinsert extends Structure {
	/** C type : strbuf */
	public strbuf ctlbuf;
	/** C type : strbuf */
	public strbuf databuf;
	/**
	 * UnixWare/Solaris compatibility.<br>
	 * C type : t_uscalar_t
	 */
	public t_uscalar_t flags;
	public int fildes;
	public int offset;
	public strfdinsert() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ctlbuf", "databuf", "flags", "fildes", "offset");
	}
	/**
	 * @param ctlbuf C type : strbuf<br>
	 * @param databuf C type : strbuf<br>
	 * @param flags UnixWare/Solaris compatibility.<br>
	 * C type : t_uscalar_t
	 */
	public strfdinsert(strbuf ctlbuf, strbuf databuf, t_uscalar_t flags, int fildes, int offset) {
		super();
		this.ctlbuf = ctlbuf;
		this.databuf = databuf;
		this.flags = flags;
		this.fildes = fildes;
		this.offset = offset;
	}
	public static class ByReference extends strfdinsert implements Structure.ByReference {
		
	};
	public static class ByValue extends strfdinsert implements Structure.ByValue {
		
	};
}
