package c;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sys/ucontext.h:706</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ucontext extends Structure {
	public NativeLong uc_flags;
	/** C type : ucontext* */
	public ucontext.ByReference uc_link;
	/** C type : stack_t */
	public sigaltstack uc_stack;
	/** C type : mcontext_t */
	public mcontext_t uc_mcontext;
	/** C type : __sigset_t */
	public __sigset_t uc_sigmask;
	/** C type : _libc_fpstate */
	public _libc_fpstate __fpregs_mem;
	public ucontext() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("uc_flags", "uc_link", "uc_stack", "uc_mcontext", "uc_sigmask", "__fpregs_mem");
	}
	/**
	 * @param uc_link C type : ucontext*<br>
	 * @param uc_stack C type : stack_t<br>
	 * @param uc_mcontext C type : mcontext_t<br>
	 * @param uc_sigmask C type : __sigset_t<br>
	 * @param __fpregs_mem C type : _libc_fpstate
	 */
	public ucontext(NativeLong uc_flags, ucontext.ByReference uc_link, sigaltstack uc_stack, mcontext_t uc_mcontext, __sigset_t uc_sigmask, _libc_fpstate __fpregs_mem) {
		super();
		this.uc_flags = uc_flags;
		this.uc_link = uc_link;
		this.uc_stack = uc_stack;
		this.uc_mcontext = uc_mcontext;
		this.uc_sigmask = uc_sigmask;
		this.__fpregs_mem = __fpregs_mem;
	}
	public static class ByReference extends ucontext implements Structure.ByReference {
		
	};
	public static class ByValue extends ucontext implements Structure.ByValue {
		
	};
}
